project:
  type: website

ipynb-filters: 
  - quarto_filter.py

execute:
  eval: false

website:
  title: "Ø¹Ø¨Ø¯ Ø§Ù„ÙƒØ±ÙŠÙ… Ø§Ù„Ø®Ø·ÙŠØ¨ - Abdelkareem Elkhateb | AI Researcher & Arabic NLP Specialist"
  image: quarto.png
  page-footer:
    center:
      - icon: github
        href: https://github.com/abdelkareemkobo
      - icon: cloud
        href: https://soundcloud.com/abdelkareem-elkhateb
      - icon: google
        href: https://kareemai.com/kareem01095134688@gmail.com
      - icon: bank
        href: https://www.upwork.com/freelancers/~016a9fea792423bb9a
      - icon: rss
        href: index.xml
  favicon: 2.svg
  open-graph: 
    locale: ar_AR
  google-analytics: "G-XFPC3M9TMG"
  twitter-card:
     creator: "@AbdelkareemElk1"
     card-style: summary
  site-url: "https://kareemai.com/"
  description: "Kareem Elkhateb personal site, a blog about machine learning, deep learning, Web development with Astro.js, FastAPI, also Arabic Natural Language Processing and Rust language."
  repo-url: https://github.com/abdelkareemkobo/karem-site
  # repo-actions: [edit]
  repo-branch: master
  navbar:
    title: false
    background: light
    pinned: true
    collapse: true
    collapse-below: lg
    left:
    - text: "ğŸ  Home"
      href: index.qmd
    - text: "ğŸ“® Blog"
      href: blog/feed.qmd
    - text: "ğŸ’­ TILs"
      file: til/index.qmd
    - text: "ğŸ“š Papers"
      file: papers.qmd
    - text: "ğŸ“– Books"
      file: publish.qmd
    right:
      - text: "ğŸ¥ Videos"
        href: https://youtube.com/@AbdelkareemElkhatib
      - text: "ğŸ’¼ Hire Me"
        href: https://www.upwork.com/freelancers/~016a9fea792423bb9a
      - text: "ğŸ’» GPUVec"
        href: https://gpuvec.com
      - icon: rss
        href: index.xml
        aria-label: "Blog RSS Feed"
      - icon: rss
        href: til/index.xml
        aria-label: "TILs RSS Feed"

  sidebar:
    - title: TILs
      pinned: true
      collapse-level: 1
      style: docked
      contents: notes/**
format:
  html:
    reference-location: document
    theme:
      light: spacelab
      dark: cyborg
    toc: true
    syntax-definitions: 
    - fomo.xml
    css: styles.css
    fontsize: 18px


