project:
  type: website

ipynb-filters: 
  - quarto_filter.py

exeucte:
  eval: false

website:
  title: "kareem's Blog"
  image: quarto.png
  page-footer:
    center:
      - icon: github
        href: https://github.com/abdelkareemkobo
      - icon: cloud
        href: https://soundcloud.com/abdelkareem-elkhateb
      - icon: google
        href: https://kareemai.com/kareem01095134688@gmail.com
      - icon: bank
        href: https://www.upwork.com/freelancers/~016a9fea792423bb9a
      - icon: rss
        href: index.xml
  favicon: 2.svg
  open-graph: 
    locale: ar_AR
  google-analytics: "G-XFPC3M9TMG"
  twitter-card:
     creator: "@AbdelkareemElk1"
     card-style: summary
  site-url: "https://kareemai.com/"
  description: "Kareem Elkhateb personal site, a blog about machine learning, deep learning, Web developement with Astrojs,fastapi aslo arabic Natural Language Processing and Rust language."
  repo-url: https://github.com/abdelkareemkobo/karem-site
  # repo-actions: [edit]
  repo-branch: master
  navbar:
    title: false
    background: light
    pinned: false
    collapse: false
    left:
    # ğŸ  ğŸ“®  ğŸ ğŸ¤ ğŸ“š ğŸ’¡ğŸ”¥ ğŸ’ª ğŸ’µ â±ï¸ ğŸ‰ 
    - text: "ğŸ‘¨ğŸ½â€ğŸ’» Blog"
      href: index.qmd
    - text: ğŸ“® Blog
      href: blog/feed.qmd
    # - text: ğŸ‘¨ğŸ½â€ğŸ’» About
    #   file: about.qmd
    # - text: ğŸ¨ Projects
    #   file: oss/opensource.qmd
    - text: TILs
      file: til/index.qmd
    - text: Papers 
      file: papers.qmd
    - text: Books
      file: publish.qmd
    right:
      - icon: rss
        href: index.xml
      - icon: rss
        href: til/index.xml

  sidebar:
    - title: TILs
      pinned: true
      collapse-level: 1
      style: docked
      contents: notes/**
format:
  html:
    reference-location: document
    theme:
      light: spacelab
      dark: cyborg
    toc: true
    syntax-definitions: 
    - fomo.xml
    # fontsize: 18px


